services:
  cilroy:
    image: "${CILROY_IMAGE:-ghcr.io/kilroybot/cilroy}:${CILROY_TAG:-latest}"
    ports:
      - "${CILROY_PUBLISHED_PORT:-12000}:12000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "CILROY_STATE_DIRECTORY=${CILROY_STATE_DIRECTORY:-/etc/cilroy}"
      - "CILROY_CONTROLLER__FACE__HOST=${CILROY_CONTROLLER__FACE__HOST:-kilroy-face-discord}"
      - "CILROY_CONTROLLER__FACE__PORT=${CILROY_CONTROLLER__FACE__PORT:-10000}"
      - "CILROY_CONTROLLER__MODULE__HOST=${CILROY_CONTROLLER__MODULE__HOST:-kilroy-module-huggingface}"
      - "CILROY_CONTROLLER__MODULE__PORT=${CILROY_CONTROLLER__MODULE__PORT:-11000}"
    volumes:
      - cilroy:/etc/cilroy
