services:
  kilroyweb:
    extends:
      file: ./kilroyweb.yml
      service: kilroyweb
    image: "${KILROYWEB_IMAGE:-kilroybot/kilroyweb}"
    build: "${KILROYWEB_PATH:-./kilroyweb}"
    depends_on:
      - grpc-web-proxy

  grpc-web-proxy:
    extends:
      file: ./grpc-web-proxy.yml
      service: grpc-web-proxy
    image: "${GRPC_WEB_PROXY_IMAGE:-kilroybot/grpc-web-proxy}"
    build: "${GRPC_WEB_PROXY_PATH:-./grpc-web-proxy}"
    depends_on:
      - cilroy

  cilroy:
    extends:
      file: ./cilroy.yml
      service: cilroy
    image: "${CILROY_IMAGE:-kilroybot/cilroy}"
    build: "${CILROY_PATH:-./cilroy}"
    depends_on:
      - kilroy-face-debug
      - kilroy-module-huggingface

  kilroy-face-debug:
    extends:
      file: ./kilroy-face-debug.yml
      service: kilroy-face-debug
    image: "${KILROY_FACE_DEBUG_IMAGE:-kilroybot/kilroy-face-debug}"
    build: "${KILROY_FACE_DEBUG_PATH:-./kilroy-face-debug}"

  kilroy-module-huggingface:
    extends:
      file: ./kilroy-module-huggingface.yml
      service: kilroy-module-huggingface
    image: "${KILROY_MODULE_HUGGINGFACE_IMAGE:-kilroybot/kilroy-module-huggingface}"
    build: "${KILROY_MODULE_HUGGINGFACE_PATH:-./kilroy-module-huggingface}"

volumes:
  cilroy:
  kilroy-face-debug:
  kilroy-module-huggingface:
  huggingface-cache:
